//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication16.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debate
    {
        public long id { get; set; }
        public string electionArea { get; set; }
        public string data { get; set; }
        public string topic { get; set; }
        public string firstCandidateList { get; set; }
        public string secondCandidateList { get; set; }
        public string status { get; set; }
        public string ZoomLink { get; set; }
    }
}
