//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication16.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class partyCandidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partyCandidate()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public long id { get; set; }
        public Nullable<long> partyId { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string nationalId { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthDay { get; set; }
        public string typeOfChair { get; set; }
        public string religion { get; set; }
        public string status { get; set; }
        public string electoralDistrict { get; set; }
    
        public virtual partyList partyList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
