//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication16.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long id { get; set; }
        public Nullable<long> candidateId { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public string paymentMethod { get; set; }
    
        public virtual partyCandidate partyCandidate { get; set; }
    }
}
